
# Just for contact links
github_id: 'elliotdickison'
twitter_id: 'elliotdickison'
contact_email: 'elliotdickison@gmail.com'

# For when we don't actually know what went wrong...
generic_error_message: 'Sorry, seems a critter has chewed through the wires someplace. Please try again later.'

